name: test_2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  fl_chart: ^0.70.1
  shared_preferences: ^2.2.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/ocean.jpg
    - assets/rain.jpeg
    - assets/birds.jpeg
    - assets/Forest.jpeg
    - assets/thunderstorm.jpeg
    - assets/white_noise.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
